### ISSUE TITLE
setting page_action in manifest is not allowed

### ISSUE THREAD

**Issue by grinono** [extend-chrome/rollup-plugin-chrome-extension#101]
adding page_action in the manifest will return 
``` [!] (plugin chrome-extension) Error: There were problems with the extension manifest. ```

page_action

```
  "page_action": {
    "browser_style": true,
    "default_icon": {
      "19": "assets/icons/icon-16.png",
      "38": "assets/icons/icon-38.png"
    },
    "default_title": "Whereami?"
  },
```

 [refs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions)

**Comment by grinono** [comment]
looks like it's not allowed in combination with "browser_action"

**Comment by AmySteam** [comment]
@grinono yeah that makes sense! Looks like the manifest validator caught that. I'm closing this issue for now 👍
