### ISSUE TITLE
How might I modify the rollup.config.js to add a "run local" script?

### ISSUE THREAD

**Issue by ogrotten** [extend-chrome/rollup-plugin-chrome-extension#102]
Due to the performance of my extension, I would like the script option to build and run a local server. Long story short: I need to build new pages/components, but reloading via the extension has a lot going on and it is therefore slow.

How would the config be built so that it would serve `./dist` on localhost

**Comment by AmySteam** [comment]
Hey @ogrotten, good question. Another user had a similar question, here's a workaround in the meantime https://github.com/extend-chrome/rollup-plugin-chrome-extension/issues/71#issuecomment-808917251 .

@jacksteamdev, do you want to add to this?

**Comment by jacksteamdev** [comment]
@ogrotten That's a tough one. AFAIK, Rollup doesn't really do progressive builds.

I'm going to take a swing at adding Vite support next week :crossed_fingers: and Vite _does_ do progressive builds! This should cover your use case.

**Comment by jacksteamdev** [comment]
@ogrotten Actually, it might be as easy as using something like [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) on `./dist` but it depends on what your pages do.
