### ISSUE TITLE
`<all_urls>` match patterns are not handled properly

### ISSUE THREAD

**Issue by andylizi** [extend-chrome/rollup-plugin-chrome-extension#110]
### Google search terms

Doesn't apply

### Describe the bug

```
TypeError: Cannot read property 'split' of undefined
    at convertMatchPatterns (node_modules\rollup-plugin-chrome-extension\src\manifest-input\convertMatchPatterns.ts:7:1)
    at Array.map (<anonymous>)
    at node_modules\rollup-plugin-chrome-extension\src\manifest-input\updateManifest.ts:55:1)
    at node_modules\rollup-plugin-chrome-extension\src\manifest-input\index.ts:252:1)
    at node_modules\rollup-plugin-chrome-extension\src\index.ts:47:1
```

### How do we reproduce?

```json
{
  "manifest_version": 3,
  "name": "foo",
  "description": "bar",
  "version": "1.0",

  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["content-script.ts"]
    }
  ]
}
```

### Expected behavior

Build success.

### Actual behavior

Build failed with the above error.

### Please complete the following information:

- Library Version: 3.6.2
- Operating System: Windows 10
- Browser: Chrome 94
- Node Version: 16.6.2

### Additional context

[Match patterns](https://developer.chrome.com/docs/extensions/mv3/match_patterns/) allow two special formats `<all_urls>` and `urn:*` which are not handled by [`convertMatchPattern()`](https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/v3.6.2/src/manifest-input/convertMatchPatterns.ts), #100.

**Comment by AmySteam** [comment]
Hey @andylizi Thanks for the bug report. @jacksteamdev will have time to look into this next week.

Most extensions use the match patterns https://*/*, http://*/* or specific sites. 

Out of curiosity, what's your use case for <all_urls>?  (https://*/*, http://*/*, file:///*, ftp and urn:*? Does your extension need access to all these schemas?

**Comment by andylizi** [comment]
My use case is basically "run this on all websites" and I didn't see the need to write `https://*/*`, `http://*/*` and `file:///*` when `<all_urls>` is sufficient. Chrome doesn't support FTP anymore and I don't actually know what `urn:` is. :joy: 

I'm using something like this as a workaround:
```diff
 const convertMatchPatterns = (m) => {
+  if (m === "<all_urls>") return m;
```
which seems to work alright.
