### ISSUE TITLE
Process manifests slightly differently

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#121]
### Expected Behavior / Situation
If a manifest has things (e.g. Service Worker, content script) that do not import scripts - link them directly.
For example, if I have
```json
{
  "content_scripts": [
    {
      "matches": ["some-site"],
      "js": ["scripts/content-script.js"]
    }
  ]
}
```
And `scripts/content-script.js` does not import anything, the end-manifest should look like
```json
{
  "content_scripts": [
    {
      "matches": ["some-site"],
      "js": ["scripts/content-script.js"]
    }
  ]
}
```

### Actual Behavior / Situation
The end-manifest would look like
```json
{
  "content_scripts": [
    {
      "matches": ["some-site"],
      "js": ["scripts/import-content-script"]
    }
  ],
  "web_accessible_resources": [
    {
      "resources": [
        "chunks/*-*.js",
        "scripts\\content-script.js"
      ],
      "matches": ["some-site"]
    }
  ]
}
```
And all that `scripts/import-content-script.js` is doing is to import `scripts/content-script.js`
```js
!function(){
  const t=JSON.parse('"scripts/content-script.js"');
  import(chrome.runtime.getURL(t));
}();
```

### Modification Proposal
To keep it simple - if the content script does not import a script, link it directly
```json
{
  "content_scripts": [
    {
      "matches": ["some-site"],
      "js": ["scripts/content-script.js"]
    }
  ]
}
```

**Comment by jacksteamdev** [comment]
@avi12 This seems like a valuable feature, I'll add this to the roadmap! :+1: 

I don't plan on doing much to the current version, I'm putting all my focus on #117, so I'll bump this issue when it's ready for testing.

**Comment by jacksteamdev** [comment]
RPCE v4 uses the IIFE format for content scripts currently. I have plans to use a dynamic import to support content script HMR, but that's further down the road. That will require a custom HMR client for both the content script and the background service worker.

@avi12 If you're interested in testing v4, I've had pretty good success with Svelte HMR in RPCE v4 with MV3. 

The official Vite Svelte boilerplate works pretty good.

```sh
npm init vite@latest
```
```sh
npm i rollup-plugin-chrome-extension@beta -D
```

Add RPCE to `vite.config.js` and put the manifest in the project root.

```jsonc
// manifest.json
{
  "manifest_version": 3,
  "action": {
    "default_popup": "index.html"
  }
}
```

You should now have HMR in the popup in Vite serve mode.

OFC to preserve state, you have to use an external store...
