### ISSUE TITLE
What is the recommended approach for using environment variables?

### ISSUE THREAD

**Issue by rbhalla** [extend-chrome/rollup-plugin-chrome-extension#123]
I've noticed that the (react) bootstrap project includes the `replace` plugin, however my understanding is this only works in the javascript files.

Ideally I would also be able to modify the manifest.json file depending on the environment too (e.g. the `host_permissions` fields to point to dev vs prod API) or maybe even public assets the extension exposes.

Do you have any recommendations for how best to do this with the plugin? Or is there potential for this plugin to have first-class support for environment variables across file types?

One way I can see this working (inspired by other bundling libraries) is allow the `manifest.json` to be defined as a `manifest.js` that exports an object instead. But I do appreciate that's quite a big change.

**Comment by mnoorenberghe** [comment]
See this answer for recent releases: https://www.extend-chrome.dev/rollup-plugin#can-i-write-my-manifest-in-typescript

For past releases you can use the `extendManifest` callback option: https://github.com/extend-chrome/rollup-plugin-chrome-extension/blame/7ed4e7bc6069037df42843045eb57dcdd748abeb/__fixtures__/extensions/mv2-extend-manifest-as-function/rollup.config.js#L20

**Comment by jacksteamdev** [comment]
Thanks @mnoorenberghe for the great answer!
