### ISSUE TITLE
when i use vue of vite build extension.  that css will lose

### ISSUE THREAD

**Issue by yvywang** [extend-chrome/rollup-plugin-chrome-extension#183]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

![image](https://user-images.githubusercontent.com/53296318/148920757-5f5b06dd-34e4-4e65-844b-efed6ca9aab2.png)

### Reproduction

![image](https://user-images.githubusercontent.com/53296318/148920921-8ebfb513-baff-49c5-9306-d05f9fa746f7.png)

### System Info

```shell
vite build
```

### Severity

blocking all usage of RPCE

**Comment by yvywang** [comment]
I found that the CSS built was not being used

**Comment by wudaxue** [comment]
I resolved it in the way shown in the figure。

![Wl4ZedvDT9](https://user-images.githubusercontent.com/31333358/149186373-e5ce7dd8-dce7-4387-9c67-67edb7d895bf.png)

by link   https://www.xiaoboy.com/topic/202109180735.html

**Comment by jacksteamdev** [comment]
Are you saying that the CSS is not working? I need more info... :hugs: 

1. Please paste the result of running this command
```sh
npx envinfo --system --npmPackages rollup-plugin-chrome-extension,vite,rollup --binaries --browsers
```
2. Please paste the `manifest.json` from `outDir`

**Comment by yvywang** [comment]
> ```shell
> npx envinfo --system --npmPackages rollup-plugin-chrome-extension,vite,rollup --binaries --browsers
> ```

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 241.83 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.1
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-11 => 4.0.1-11
    vite: ^2.7.10 => 2.7.10
    --------------------------------------------------------------------------------------------------------
paste manifest.json from outDir 
    {
  "name": "weheatmap",
  "version": "1.0",
  "description": "Build an Extension!",
  "manifest_version": 3,
  "content_scripts": [
    { "matches": ["<all_urls>"], "js": ["script/content.js"] }
  ],
  "options_ui": { "page": "options/index.html" },
  "action": { "default_popup": "popup/index.html" },
  "permissions": []
}

**Comment by yvywang** [comment]
> Are you saying that the CSS is not working? I need more info... 🤗
> 
> 1. Please paste the result of running this command
> 
> ```shell
> npx envinfo --system --npmPackages rollup-plugin-chrome-extension,vite,rollup --binaries --browsers
> ```
> 
> 2. Please paste the `manifest.json` from `outDir`

I found maybe question in "vite:build-html" this plugin , because "build.input" not .html files, so not inject tags 
![image](https://user-images.githubusercontent.com/53296318/150057132-b772c899-2132-488b-8e48-a04bcedf88a0.png)

**Comment by jacksteamdev** [comment]
Thanks for helping me understand! 

It looks like the problem is that in `vite build`, the HTML files don't have CSS tags.

I can add a test to make sure that all HTML files run through the `vite:build-html` plugin.

**Comment by yvywang** [comment]
> Thanks for helping me understand!
> 
> It looks like the problem is that in `vite build`, the HTML files don't have CSS tags.
> 
> I can add a test to make sure that all HTML files run through the `vite:build-html` plugin.

Thanks!

**Comment by jacksteamdev** [comment]
@yvywang That was a great insight about "vite:build-html"! :mage_man: 

We're using Vite's HTML plugins now, and there are e2e tests in place to make sure HTML builds work in the future.

Would you like to give it a try with the most recent beta release? :pray:

**Comment by jacksteamdev** [comment]
The API has changed a little, I updated this [DEV article](https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7) with new instructions.
