### ISSUE TITLE
Vite Build Error

### ISSUE THREAD

**Issue by keyding** [extend-chrome/rollup-plugin-chrome-extension#193]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

`pnpm dev` doesn't have any problems, but `pnpm build` gives an error when building the package.

**/dist/manifest.json**

![image](https://user-images.githubusercontent.com/20431351/150667181-aa446e2d-8761-4c07-b3f4-bce3369e15b5.png)

----- 
```pnpm build```
![image](https://user-images.githubusercontent.com/20431351/150667367-487fe136-281a-4328-8c63-78111174121c.png)
-----

If the order of vue() and chromeExtension() is switched, the package will work. However, **the popup page does not exist**.

**vite.config.js** 

![image](https://user-images.githubusercontent.com/20431351/150667141-66f08dda-4d2c-427a-b8e2-c35fa472c82b.png)

**/dist**

![image](https://user-images.githubusercontent.com/20431351/150667156-154daa82-2283-4140-82c3-948086864620.png)

**/dist/index.html**

![image](https://user-images.githubusercontent.com/20431351/150667166-a543dac5-350c-4bb3-bfc6-e710e79c90e9.png)

### Reproduction

https://github.com/keyding/vite-rpce-test

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 62.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.99
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-12 => 4.0.1-12
    vite: ^2.7.2 => 2.7.13
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
@keyding Thanks for the great repo and details!

I'm going to add an e2e test for the Vite Vue starter project to cover this use case.

**Comment by AndreasNasman** [comment]
Having similar problems also on my Mac. 

`pnpm run dev` and `pnpm run build` both worked the first couple of runs but seem to fail after that.

`pnpm run dev` stops at `Building Chrome Extension files...`  
<img width="864" alt="image" src="https://user-images.githubusercontent.com/17124245/152060388-b50a84ad-78e7-4292-ae06-ee9f1ce67bff.png">
and `pnpm run build` fails with the same error message @keyding posted
<img width="649" alt="image" src="https://user-images.githubusercontent.com/17124245/152060892-f64878cd-6aa9-469a-bacd-13aba3ed1dea.png">

Removing `dist` and `node_modules` fixed it for a while but not for long. I'm also trying to build with Vue.

– Andreas

**Comment by jacksteamdev** [comment]
@keyding Thanks for helping push official Vue support! I've added e2e tests for build and HMR.

There's a new API, you can check it out in the PR I made to your repro: [Working example config with new plugin API by jacksteamdev · Pull Request #1 · keyding/vite-rpce-test](https://github.com/keyding/vite-rpce-test/pull/1)

**Comment by jacksteamdev** [comment]
@AndreasNasman I've done a major rewrite that should smooth out those issues you were running into.

I've updated the article on DEV, you can check it out for updated instructions.

**Comment by keyding** [comment]
> @keyding Thanks for helping push official Vue support! I've added e2e tests for build and HMR.
> 
> There's a new API, you can check it out in the PR I made to your repro: [Working example config with new plugin API by jacksteamdev · Pull Request #1 · keyding/vite-rpce-test](https://github.com/keyding/vite-rpce-test/pull/1)

@jacksteamdev Thanks very much!

**Comment by AndreasNasman** [comment]
> @AndreasNasman I've done a major rewrite that should smooth out those issues you were running into.
> 
> I've updated the article on DEV, you can check it out for updated instructions.

Thanks a lot for your hard work! Works flawlessly now! ❤️
