### ISSUE TITLE
v4: `build` script doesn't package JS files, `dev` works

### ISSUE THREAD

**Issue by mnoorenberghe** [extend-chrome/rollup-plugin-chrome-extension#194]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

1. Follow the tutorial from https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7 and get it working with `yarn run dev`. 
2. Build with `yarn run build`

Notice that there are no JS files in the `dist` directory. If you load the extension then it will give an error in the browser that it can't load the script files.

I tried with both manifest v2 and v3 using React and without any plugin. This is maybe related to #193 but in my case there is no build error.

### Reproduction

MV3 React: https://github.com/mnoorenberghe/rpce-v4-missing-js
MV2, no plugins: https://github.com/mnoorenberghe/rpce-v4-missing-js/tree/mv2_without_react

I checked in the `dist/` directory for both after `yarn run build` to make it easy to confirm that the JS isn't packaged.

### Logs

```shell
$ yarn run build -l info
yarn run v1.22.17
$ tsc && vite build -l info
vite v2.7.13 building for production...
✓ 1 modules transformed.
dist/manifest.json     0.12 KiB
dist/index.html        0.34 KiB
dist/src/favicon.svg   1.49 KiB
✨  Done in 4.14s.
```

Browser: `Loading failed for the module with source “moz-extension://6a187b60-0094-4fc4-a996-c63b70cbd8c2/src/main.js”.`

### System Info

(The suggested command is giving an error so manually providing details)

$ node --version
v17.3.0
```
```
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/firefox-webext-browser": "^94.0.1",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vitejs/plugin-react": "^1.0.7",
    "rollup-plugin-chrome-extension": "^4.0.1-12",
    "typescript": "^4.4.4",
    "vite": "^2.7.2"
  }
```
macOS 12.1 (21C52)



### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
@mnoorenberghe Thanks for pointing this out! I'm going to add e2e tests for the Vite starter projects.

**Comment by jacksteamdev** [comment]
@mnoorenberghe I tested your MV3 repro against the most recent beta version (v4.0.1-16), and everything seems to be working!

The build files look a lot different b/c we're sending the HTML files through Vite's build pipeline instead of a custom one.

You can check it out on this PR I made to your repo: https://github.com/mnoorenberghe/rpce-v4-missing-js/pull/1
