### ISSUE TITLE
Stuck at "Building Chrome Extension files..."

### ISSUE THREAD

**Issue by Wombarly** [extend-chrome/rollup-plugin-chrome-extension#198]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When I follow the exact steps in the guide link in the readme. I get stuck at the building stage, it hangs at `Building Chrome Extension files...`

Guide in question: https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7

### Reproduction

```
npm init vite@latest // select `react`
npm i rollup-plugin-chrome-extension@beta -D
```

```
// vite.config.js

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { chromeExtension } from "rollup-plugin-chrome-extension";

export default defineConfig({
  plugins: [react(), chromeExtension()],
});
```

```
// manifest.json
{
  "manifest_version": 3,
  "action": { "default_popup": "index.html" }
}
```

```
npm run dev
```

### Logs

```shell
npm run dev

> fanfictioner@0.0.0 dev
> vite

Pre-bundling dependencies:
  react
  react-dom
  react/jsx-dev-runtime   
(this will be run only when your dependencies or config have changed)
> Resolving CRX watch config from "D:/Projects/Git/fanfictioner/vite.config.js"

  vite v2.7.13 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 1111ms.

Building Chrome Extension files...
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.00 GB / 31.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)     
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-12 => 4.0.1-12
    vite: ^2.7.2 => 2.7.13
```

### Severity

blocking all usage of RPCE

**Comment by Wombarly** [comment]
Duplicate of #137 didn't release untill after I posted the issue 😓

**Comment by jacksteamdev** [comment]
@Wombarly I've done a major rewrite in v4.0.1-16, would you be interested in giving this another look?

I see you're using Windows, and I don't have a Windows computer that I can test on, so no guarantees, but your feedback would be awesome.

The API has changed a little; I've updated the instructions on this DEV article: 

[Create a Vite-React Chrome Extension in 90 seconds - DEV Community 👩‍💻👨‍💻](https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7)
