### ISSUE TITLE
The script tag in options_page html file is not loaded when using `vite` in development.

### ISSUE THREAD

**Issue by ekilzen** [extend-chrome/rollup-plugin-chrome-extension#199]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

The script tag in `"options_page": "options.html` is not loaded when using `vite` in development.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-1mk1cy?file=src/manifest.json

1. run `npm run dev`
2. should generate `main.js`, which is a script of `options.html`, in `dist` folder 

BTW, the `vite build` works perfect, I don't know if it is even a bug or not.
I am using nodemon to watch files and run `vite build` right now.

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.01 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/Library/pnpm/node
    Yarn: 1.22.11 - ~/Library/pnpm/yarn
    npm: 8.1.0 - ~/Library/pnpm/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 98.1.35.100
    Chrome: 98.0.4758.80
    Edge: 98.0.1108.43
    Firefox: 81.0.2
    Firefox Developer Edition: 78.0
    Safari: 15.3
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-12 => 4.0.1-12 
    vite: ^2.7.13 => 2.7.13
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@ekilzen First, thank you for the truly nice StackBlitz repro! It made debugging this much easier. :clap: 

I got things working with the newest beta release (v4.0.1-16). [Working StackBlitz repro fork](https://stackblitz.com/edit/vitejs-vite-4jerhk?file=vite.config.ts)

The API has changed as of beta release v4.0.1-14, just import the manifest in `vite.config.ts`:

![image](https://user-images.githubusercontent.com/23390212/154866329-0cc72739-3eae-4fbc-a5fb-f8b743b48390.png)

Paths in the manifest are now relative to the [project root directory](https://vitejs.dev/config/#root), so I moved `manifest.json` to reflect this.
