### ISSUE TITLE
Manifest: schema for web_accessible_resources do not have the same items as Google Documentation or Chrome

### ISSUE THREAD

**Issue by fish-in-the-sea** [extend-chrome/rollup-plugin-chrome-extension#237]
### Build tool

Rollup

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

As per Chrome documentation, `web_accessible_resources` required items are `matches` and `extension_ids`.
The schema used by the rollup chrome plugin need `matches` and `extensions` which trigger an error when we try to load the unpacked extension.

```
Error 
Invalid value for 'web_accessible_resources[0]'. Entry must at least have resources, and one other valid key.
```

### Reproduction

https://github.com/fish-in-the-sea/huxley-comics-inspector/tree/issue/web-accessible-resources

- Clone the repo
- `$ npm install`
- `$ npm run build`
- Open Chrome Extension page ( chrome://extensions/ )
- Click on "load unpacked" and select the `dist` folder

### Logs

```shell
Invalid value for 'web_accessible_resources[0]'. Entry must at least have resources, and one other valid key.
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 18.07 GB / 31.58 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
  npmPackages:
    rollup: ^2.40.0 => 2.70.0
    rollup-plugin-chrome-extension: ^3.5.6 => 3.6.7
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@fish-in-the-sea Nice catch! 🎣 

Should be fixed in the repo, still need to release to NPM.

**Comment by bluecaret** [comment]
@jacksteamdev Is this on NPM yet? I'm on version 3.6.10 but still am seeing this issue.
