### ISSUE TITLE
manifest inject content_scripts "css" config fail

### ISSUE THREAD

**Issue by yvywang** [extend-chrome/rollup-plugin-chrome-extension#243]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

When I used the manifest.json configuration for content_scripts CSS configuration, I found that it was not handled during compilation, I thought may be this is a BUG

### Reproduction

<img width="766" alt="image" src="https://user-images.githubusercontent.com/53296318/158953988-f6d74de6-c2d6-405e-9ec6-85abe3b14133.png">

look like on plugin package `plugin-manifest.ts` for CSS configuration is not compiled

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 130.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.3
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-16 => 4.0.1-16
    vite: ^2.7.10 => 2.7.10
```

### Severity

blocking an upgrade

**Comment by yvywang** [comment]
I currently use it in the `Content.ts` import `CSS file`, i think maybe this seem a little strange 😂

**Comment by yvywang** [comment]
I found the same problem with the `icons` configuration

**Comment by yvywang** [comment]
I found the same problem with the `manifest.json`  `icons?: chrome.runtime.ManifestIcons | undefined` configuration

**Comment by jacksteamdev** [comment]
@yvywang You're right! Importing CSS into the content script works, and the output CSS file will end up in the manifest.

`manifest.content_scriptsn[n].css` hasn't been implemented yet 😅 I plan to pass CSS through Vite, so things like SCSS in the manifest should work in the future.

#### Workaround
Try putting icons and manifest CSS files in `public` for now. Files and folders in public are copied directly into `dist`.

```
// files
- manifest.json
- public/
	- styles.css
- dist/
	- manifest.json
	- styles.css
```

```jsonc
// manifest.json
{
  "content_scripts": [
    "css": ["styles.css"]
  ]
}
```

**Comment by jacksteamdev** [comment]
@yvywang The most recent beta release (RPCE@4.0.1-18) adds true HMR to content scripts, including imported CSS.

You can check it out here: [Real Vite-React HMR in Chrome Extension Content Scripts - DEV Community 👩‍💻👨‍💻](https://dev.to/jacksteamdev/real-vite-react-hmr-in-chrome-extension-content-scripts-40di)

**Comment by yvywang** [comment]
> 
Ok thank you for your help

**Comment by yvywang** [comment]
> @yvywang You're right! Importing CSS into the content script works, and the output CSS file will end up in the manifest.
> 
> `manifest.content_scriptsn[n].css` hasn't been implemented yet 😅 I plan to pass CSS through Vite, so things like SCSS and HMR for styles in the manifest should work in the future.
> 
> #### Workaround
> Try putting icons and manifest CSS files in `public` for now. Files and folders in public are copied directly into `dist`.
> 
> ```
> // files
> - manifest.json
> - public/
> 	- styles.css
> - dist/
> 	- manifest.json
> 	- styles.css
> ```
> 
> ```js
> // manifest.json
> {
>   "content_scripts": [
>     "css": ["styles.css"]
>   ]
> }
> ```

ok , thank you for your help 😂
