### ISSUE TITLE
Content-script HMR works only for css

### ISSUE THREAD

**Issue by vovsemenv** [extend-chrome/rollup-plugin-chrome-extension#254]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Content-script HMR works only for css

### Reproduction

guide fro https://dev.to/jacksteamdev/real-vite-react-hmr-in-chrome-extension-content-scripts-40di#add-a-content-script

### System Info

```shell
last chrome
```

### Severity

annoyance

**Comment by vovsemenv** [comment]
@jacksteamdev bug or feature?

**Comment by jacksteamdev** [comment]
@vovsemenv The article encourages the reader to try JS HMR, but doesn't specify what changes to make. 

Please provide a detailed description of how JS HMR doesn't work. 🙏

**Comment by aptash** [comment]
In my case, first I have to remove the "dist" folder to see the changes. HMR doesn't work even with CSS changes.

**Comment by jacksteamdev** [comment]
> I'm on Windows 10.

Probably related to #137

> 18:13:14 [crx] files start ../../../../../dist

@aptash `../../../../../dist` makes me think that path resolution isn't working for Windows. Is a `dist` folder created five folders up?

**Comment by jacksteamdev** [comment]
@vovsemenv Closing b/c issue doesn't provide a minimal repro or even system info.
