### ISSUE TITLE
[vite:load-fallback] Could not load /crx-client-preamble: ENOENT: no such file or directory, open '/crx-client-preamble

### ISSUE THREAD

**Issue by exherb** [extend-chrome/rollup-plugin-chrome-extension#261]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

vite build --mode=development --watch

-> 

[vite:load-fallback] Could not load /crx-client-preamble: ENOENT: no such file or directory, open '/crx-client-preamble'

without dist directory appear

### Reproduction

gitHub.com/exherb/rollup-plugin-chrome-extension-bug

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
    Memory: 41.15 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.2 - /usr/local/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 99.0.4844.74
    Firefox: 95.0.2
    Safari: 15.4
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-18 => 4.0.1-18
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@exherb This plugin doesn't currently support `vite build --watch`. I noticed your example repro only has a background page, do you mind sharing your use case?

If your project does have HTML or content scripts, have you tried `vite serve`? That should work with HMR in both contexts. Even if you're not using a framework that supports HMR, it will reload the extension as you make changes.

Possibly related to #255

**Comment by exherb** [comment]
It’s just a example, so I don’t put any code into it.

If vite serve works, this issue should close
