### ISSUE TITLE
HTML pages in `chrome_url_overrides` not parsed from manifest

### ISSUE THREAD

**Issue by zOwNaToR** [extend-chrome/rollup-plugin-chrome-extension#267]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

I builded an extension that runs on new tab with vite, react and this plugin.
When i launch "npm run dev" the dist folder does not contain index.html and when i try to load the extension in chrome i receive the error: 
File: ~/MYPROJECTPATH/dist
Error: File not found: index.html. Could not load manifest.

### Reproduction

Clone my repo: https://github.com/zOwNaToR/annotate
Run npm install, npm run build and try to install the extension

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 10.21 GB / 15.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 96.0
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-18 => 4.0.1-18 
    vite: ^2.8.0 => 2.8.6
```

### Severity

blocking all usage of RPCE

**Comment by zOwNaToR** [comment]
I found a way to make this warning, but this not the correct way and must be fixed.
I changed my manifest.json from
`{
  "manifest_version": 3,
  "name": "Annotate 2",
  "version": "1.0.0",
  "chrome_url_overrides" : {
    "newtab": "index.html"
  }
}
`
to
`{
  "manifest_version": 3,
  "name": "Annotate 2",
  "version": "1.0.0",
  "action": {
    "default_popup": "index.html"
  },
  "chrome_url_overrides" : {
    "newtab": "index.html"
  }
}
`

Adding 'action' forces the 'npm run dev' process to include index.html in dist folder

**Comment by jacksteamdev** [comment]
It looks like this code omits `chrome_url_overrides` when parsing the manifest.

https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/5003541ab87417fe705b8ccc749b1a4ebc687102/src/node/helpers.ts#L78-L90

We need to add the URL overrides defined in [Overriding Chrome pages - Chrome Developers](https://developer.chrome.com/docs/extensions/mv3/override/#manifest).

I'll do this when I have time, but please feel free to make a PR that includes an integration test in [rollup-plugin-chrome-extension/tests/mv3](https://github.com/extend-chrome/rollup-plugin-chrome-extension/tree/main/tests/mv3)
