### ISSUE TITLE
[vite + svelte-ts] index.ts in popup/index.html can't be bundled without type="module" attribute

### ISSUE THREAD

**Issue by theaspirational** [extend-chrome/rollup-plugin-chrome-extension#268]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

![image](https://user-images.githubusercontent.com/48733736/161014912-d4507846-62a4-4109-af02-246f6bf3415f.png)

but when I add `type="module" attribute` to popup:

![image](https://user-images.githubusercontent.com/48733736/161015168-64867493-23e3-4f87-98bf-e673d2093c88.png)

### Reproduction

[my-repo](https://github.com/theaspirational/huntbahn-ext-svelte-dev/tree/vite)

### System Info

```shell
System:
    OS: macOS 11.6.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Memory: 2.79 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 99.1.36.119
    Chrome Canary: 102.0.4974.2
    Safari: 15.3
  npmPackages:
    rollup: ^2.36.2 => 2.70.1 
    rollup-plugin-chrome-extension: ^4.0.1-18 => 4.0.1-18 
    vite: ^2.9.0 => 2.9.0
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
When using Vite, paths in HTML files should always be valid module paths.

```html
<script src="index.ts">
```

should be something like

```html
<script src="./index.ts">
```

This is a Vite limitation. Vite converts HTML files into JS files internally and script tags become import statements.

```js
// vite can't resolve this
import 'index.ts'

// this should work
import './index.ts'
```

**Comment by jacksteamdev** [comment]
I haven't tested RPCE with Svelte yet, but true Svelte support coming soon. It will probably take some extra work, just like React and Vue
