### ISSUE TITLE
Content Scripts not found when using vite

### ISSUE THREAD

**Issue by mismith** [extend-chrome/rollup-plugin-chrome-extension#270]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When trying to run `build`:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/638816/161342755-4e7ec80f-a15d-425f-8670-700b9ba80ee9.png">

When trying to `dev`:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/638816/161343629-82e15f75-f82e-43c2-8f7f-c41ad6ba6437.png">

Likely both stemming from the same issue. I think it has something to do with the `manifest.json` and `content_script.js` files being nested in the `src/` directory, since if I move them to the root, it works. (But in my specific use case, that causes other issues, like icons not loading from _within_ the `src/` directory 😅)

### Reproduction

https://github.com/mismith/chrome-extension-bug

Repro repo file tree:
```sh
tree -I .git -I node_modules
.
├── package-lock.json
├── package.json
├── src
│   ├── content_script.js
│   └── manifest.json
└── vite.config.js

1 directory, 5 files
```

### `vite.config.js`

```js
import { defineConfig } from "vite";
import { chromeExtension } from "rollup-plugin-chrome-extension";

import manifest from "./src/manifest.json";

export default defineConfig({
	build: {
		rollupOptions: {
			input: "./src/manifest.json",
		},
	},
	plugins: [
		chromeExtension({
			manifest,
			contentScripts: { preambleCode: false },
		}),
	],
});
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 336.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Chrome Canary: 102.0.4977.0
    Firefox: 94.0.2
    Safari: 15.4
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-18 => 4.0.1-18 
    vite: ^2.8.6 => 2.9.1
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
Paths in the manifest are relative to `viteConfig.root`, not the manifest file.

I find that putting `manifest.json` in the project root next to `package.json` makes it easier to think about 👍 

```
.
├── package-lock.json
├── package.json
├── manifest.json
├── src
│   └── content_script.js
└── vite.config.js
```

```json
{
  "content_scripts": [{
    "js": ["src/content_script.js"]
  }]
}
```

**Comment by jacksteamdev** [comment]
@mismith Sorry, I read your issue again today; now I see that you tried putting the manifest in the root. :sweat_smile: 

The next release (see #259) will actively copy images from the manifest, so you should be able to have icons in `src`.

**Comment by jacksteamdev** [comment]
Related to #226

**Comment by mismith** [comment]
@jacksteamdev I did eventually get things to 'work', but I think the end result is still kind of odd / against my intuition.

Specifically, even when `manifest.json` is nested within `src`, I still need to specify `src/`-prefixed paths for some (but not all) things. And when I do, some things (popup.js/popup.html, I can't quite recall) get output to `dist/src` still nested, whereas others don't.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/638816/162145082-f7c34b45-1666-4049-b4b3-460571ce98a8.png">

I suspect/hope that the new update that processes icons will solve all this 🤞 

That said, I also say another issue where I would get pretty constant console errors in all/any webpages if a RPCE-launched hot-reloading chrome extension script was stopped—it seems as the though the hot reloaded kept running/leaking/polluting even after it should have disappeared. Hopefully this rings a bell and you have a fix in the works already!

**Comment by jacksteamdev** [comment]
@mismith Manifest assets are working as of v4.0.1-22! The paths inside `manifest.json` are relative to the [project root](https://vitejs.dev/config/#root) or files in the [public directory](https://vitejs.dev/guide/assets.html#the-public-directory). I wrote an article on advanced configs that includes details on [manifest assets and supported locations](https://dev.to/jacksteamdev/advanced-config-for-rpce-3966#manifest-icons-and-public-assets). The tests also have working examples of [public folder assets](https://github.com/extend-chrome/rollup-plugin-chrome-extension/tree/main/tests/mv3/with-public-dir) and [copied assets](https://github.com/extend-chrome/rollup-plugin-chrome-extension/tree/main/tests/mv3/with-copied-assets).
