### ISSUE TITLE
In building the background using fail. on beta version

### ISSUE THREAD

**Issue by yvywang** [extend-chrome/rollup-plugin-chrome-extension#275]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [X] In the terminal

### Describe the bug

when i use `background.ts` on `manifest.json` config
```json
  "background": {
    "service_worker": "src/script/background.ts"
  },
  ```
The building of the construction `import 'http://localhost:8088/src/script/background.ts;`
first , i think in chrome browser don't deal with `.ts` files, and look like `service-worker-loader.js` it not work🥲

### Reproduction

<img width="713" alt="image" src="https://user-images.githubusercontent.com/53296318/162156539-69c5b9c4-bd37-497c-b430-cc8c682675c1.png">

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.3
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-16 => 4.0.1-16
    vite: ^2.7.10 => 2.7.10
```
```


### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
These files come from the Vite Dev Server. Vite transforms a TS file into JavaScript, then serves it to the browser over HTTP. The HTTP response has a content type of "application/javascript" or "text/javascript", so Chrome doesn't pay attention to the file extension.

Since the background service worker is served from Vite, a development extension won't work if the dev server isn't running (it can't retrieve the background page).

Are you getting an error when you try to load your extension? Maybe you can post an example or screenshot?

**Comment by jacksteamdev** [comment]
We should document how the background loader works in development.

**Comment by jacksteamdev** [comment]
@yvywang Are you getting an error when you try to load your extension? Maybe you can post an example or screenshot?

**Comment by yvywang** [comment]
> ```js
> import 'http://localhost:8088/src/script/background.ts;
> ```
> 
> These files come from the Vite Dev Server. Vite transforms a TS file into JavaScript, then serves it to the browser as an HTTP response. The HTTP response has a content type of "application/javascript" or "text/javascript", so Chrome doesn't pay attention to the file extension.
> 
> Since the background service worker is served from Vite, a development extension won't work if the dev server isn't running (it can't retrieve the background page).
Thanks for helping me understand!

**Comment by yvywang** [comment]
> ```js
> import 'http://localhost:8088/src/script/background.ts;
> ```
> 
> These files come from the Vite Dev Server. Vite transforms a TS file into JavaScript, then serves it to the browser as an HTTP response. The HTTP response has a content type of "application/javascript" or "text/javascript", so Chrome doesn't pay attention to the file extension.
> 
> Since the background service worker is served from Vite, a development extension won't work if the dev server isn't running (it can't retrieve the background page).

i found out you were right by learned about `Service Worker` log
thanks for answering my question efficiently and helping me understand ! 🌹
