### ISSUE TITLE
MV3: Invalid path separator in the generated manifest.json on Windows

### ISSUE THREAD

**Issue by nerblock** [extend-chrome/rollup-plugin-chrome-extension#293]
### Build tool

Rollup

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

When building a project for MV3 with https://github.com/extend-chrome/ts-react-boilerplate/ on a Windows machine the content script can't be loaded, because the path separators in the `web_accessible_resources` section in the generated `dist/manifest.json` file are incorrecty converted to Windows style path separators:

```
  "web_accessible_resources": [
    {
      "resources": [
        "chunks\\*-*.js",
        "content\\index.js"
      ],
      "matches": [
        "https://*/*",
        "http://*/*"
      ]
    }
  ]
```

### Expected behavior

manifest.json should contain Unix style path separators:

```
  "web_accessible_resources": [
    {
      "resources": [
        "chunks/*-*.js",
        "content/index.js"
      ],
      "matches": [
        "https://*/*",
        "http://*/*"
      ]
    }
  ]
```

### Actual behavior

Running `npm run build` on a Linux machine (or in WSL) generates `dist/manifest.json` with `/` (slash) as path separator.

Running `npm run build` on a Windows machine generates `dist/manifest.json` with `\` (backslash) as path separator.

### Reproduction

1. clone the repository https://github.com/extend-chrome/ts-react-boilerplate/ on a Windows machine
2. Modify `src/manifest.json` for MV3:
```
{
  "name": "mv3",
  "manifest_version": 3,
  "content_scripts": [
    {
      "js": [
        "content/index.ts"
      ],
      "matches": [
        "https://*/*",
        "http://*/*"
      ]
    }
  ]
  "action": {
    "default_title": "Popup",
    "default_popup": "pages/popup/index.html"
  }
}
```
4. open a powershell terminal
5. run `npm run build`
6. check the contents of dist/manifest.json

### System Info

```shell
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    Memory: 1.30 GB / 15.91 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.88
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    rollup: ^2.56.3 => 2.70.1
    rollup-plugin-chrome-extension: ^3.6.1 => 3.6.7
```

### Severity

blocking all usage of RPCE (on Windows)

**Comment by nerblock** [comment]
I went through the source and realized that the problem is in fact in `rollup-plugin-chrome-extension`. It has different code paths for MV2 and MV3, and MV3 support looks unfinished.

Here is a quick fix:

In `node_modules/rollup-plugin-chrome-extension/src/manifest-input/updateManifest.ts`  in the `updateManifestV3` function find this part:
```
    const resources = [
      `${chunkFileNames
        .split('/')
        .join('/')
        .replace('[format]', '*')
        .replace('[name]', '*')
        .replace('[hash]', '*')}`,
      ...cache.contentScripts.map((x) =>
        path.relative(cache.srcDir, x),
      ),
    ];
```
and replace with this:
```
    const resources = [
      slash(`${chunkFileNames
        .split('/')
        .join('/')
        .replace('[format]', '*')
        .replace('[name]', '*')
        .replace('[hash]', '*')}`),
      ...cache.contentScripts.map((x) =>
        slash(path.relative(cache.srcDir, x)),
      ),
    ];
```
Basically one needs to wrap the paths in the slash() function to make them work on Windows.

**Comment by nerblock** [comment]
Originally reported at https://github.com/extend-chrome/ts-react-boilerplate/issues/6

**Comment by jacksteamdev** [comment]
@nerblock Your reasoning looks sound! I've got some plans to open v3 back up for bug fixes soon. I'll let you know when the repo is ready and we can move on this.

**Comment by nerblock** [comment]
@jacksteamdev I opened a pr: #308

**Comment by nerblock** [comment]
Closing this as the pr has been merged. 👍
