### ISSUE TITLE
Inconsistent readme

### ISSUE THREAD

**Issue by ManUtopiK** [extend-chrome/rollup-plugin-chrome-extension#32]
**Describe the bug**
There are some mistakes in the readme:
```
Create a rollup.config.js file in your project root.

// rollup.config.json

```
js or json?
```
Add these scripts to your project.json file.

// package.json
```
project.json or package.json?

**Comment by AmySteam** [comment]
Thank you for pointing these out! All feedback and pull requests are welcome.

Good luck with your chrome extension development. If you need any help with the chrome web store, [check out our channel](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg)!

Amy
