### ISSUE TITLE
Use postcss to compile styles

### ISSUE THREAD

**Issue by MickeyMiao7** [extend-chrome/rollup-plugin-chrome-extension#38]
### Is your feature request related to a problem? Please describe.

It looks like the plugin lacks the capability to compile the .less files.

The `manifest.json` looks like the below:

```
...
"content_scripts": [{
    "css": [
      "styles/content.less"
    ],
  }],
...
```

After building, the .less suffix remains unchanged in the output `manifest.json` and less files are not compiled.

### Describe the solution you'd like

Support less file compilation

### Describe alternatives you've considered

I may use external plugin for less compilation, such as `rollup-plugin-less`. The usage should be like `typescript` compilation.

```
{
    input: "manifest.json",
    output: {
      dir: "dist",
      format: "esm",
    },
    plugins: [
      chromeExtension(),
      simpleReloader(),

      typescript(),
      less(),
      
      resolve(),
      commonjs()
     ]
}

```

**Comment by jacksteamdev** [comment]
@MickeyMiao7 This is a great idea! I may not be able to implement this feature very soon, but please make a PR if you have the time.

Usually I use [`rollup-plugin-postcss`](https://github.com/egoist/rollup-plugin-postcss) for styles, but it only supports style imports in JS/TS files.

We should follow [their example](https://github.com/egoist/rollup-plugin-postcss#with-sassstylusless), and support Sass or Less automatically when `node-sass` or `less` is installed. I want to keep `rollup-plugin-chrome-extension` configuration simple as possible.

When we do add this feature, we should only process the CSS/SCSS/LESS files that are in the manifest. There are other plugins that handle CSS imported into JS files very well, and I imagine that there are many side cases for something like that.

**Comment by jacksteamdev** [comment]
I'm closing this issue since it's been open for a while and hasn't gained traction. PR's are still welcome!

**Comment by nstringham** [comment]
it would also be nice if this worked for HTML like this
```html
<link rel="stylesheet" href="popup.scss" />
```
