### ISSUE TITLE
Background scripts are unable to respond messages asynchronously

### ISSUE THREAD

**Issue by marco-lavagnino** [extend-chrome/rollup-plugin-chrome-extension#48]
### Google search terms

rollup chrome extension plugin async messages background script

### Describe the bug

Compiling an extension with the plugin causes background scripts to be unable to respond messages using `sendResponse`, when receiving a single with `chrome.runtime.onMessage.addListener()`.

### How do we reproduce?
Creating an extension with these files:

**contentScript.js**

```
chrome.runtime.sendMessage({'test':'test'}, result => result && alert(result))
```

**background.js**
```
chrome.runtime.onInstalled.addListener(function() {
  chrome.runtime.onMessage.addListener(
    (request, sender, sendResponse) => {
      setTimeout(() =>{
        sendResponse('it works')
      }, 500)
      return true
    }
  );
});
```
I've created [a repo with the manifest.json and rollup.config.js files](https://github.com/marco-lavagnino/rollup_bug_report). You can clone it and replicate the issue.

### Expected behavior

In the case above, an alert with the message 'it works' should pop up. Note that that's what happens if using the extension uncompiled.

### Actual behavior

The port gets closed when it's not supposed to.

### Screenshots

![image](https://user-images.githubusercontent.com/8427482/88240478-a1650b00-cc5d-11ea-9424-1630acbf686c.png)

### Please complete the following information:

- Library Version: 3.2.0
- Operating System: macOS 10.14.6
- Browser: Chrome 83.0.4103.116
- Node Version: 14.2.0

### Additional context

-

**Comment by jacksteamdev** [comment]
Thanks for putting together this great issue! 💯 I'll take a look this afternoon.

This is related to the way we support Rollup's code-splitting, ESM, and wake events for the background page.

The bug is probably here:
https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/0e51a03ecbca251bfb23c792f9f31ce561fb1e74/src/manifest-input/browser/captureEvents.ts#L18-L26

The event handler needs to return true if the third argument (`sendResponse`) is defined.

**Comment by jacksteamdev** [comment]
Whew! 😅 That wasn't as easy as I thought it would be. It took me a few days to get it working according to specs, but I think we've got it and there are tests written for it. This feature was released in v3.3.0.

@marco-lavagnino This is a valuable addition to this plugin. Thanks again for taking the time to put this issue together.

**Comment by marco-lavagnino** [comment]
Wow! What a great work! Is there any way I can send some bucks your way?

**Comment by jacksteamdev** [comment]
Sure! Thanks for the support 😍 . Our donation site is https://ko-fi.com/jacksteam
