### ISSUE TITLE
Manifest v2 options_ui isn't bundling associated files

### ISSUE THREAD

**Issue by WillNeill** [extend-chrome/rollup-plugin-chrome-extension#51]
### Google search terms

Google terms for `chrome extension options page` and `options_ui` with rollup.

### Describe the bug

Chrome (and other browsers) provide two methods to specify an options page for users.
See official documentation here: https://developer.chrome.com/extensions/options 

This is achieved by specifying a reference to an options page in `manifest.json` using either:

1. `options_page` (open options in a new tab)
2. `options_ui` (show options as a native UI popup on extensions page)

At the moment (v3.3.0) the first method (`options_page`) works. The second option unfortunately does not work.

### How do we reproduce?

This issue relates to Manifest version 2.

1. Create options.html and options.js files in the root directory (use the [Chrome examples](https://developer.chrome.com/extensions/options ))
2. Add `options_ui` to `manifest.json`

```JSON
"options_ui": {
    "page": "options.html",
    "open_in_tab": false
  },
```

### Expected behavior

In the case of `options_page` the `options.html` and associated JS and CSS are copied into the `dist` bundle. The same behaviour should apply for `options_ui` if present in `manifest.json`.

### Actual behavior

At the moment, only the `options_page` method works. It would be great to have the second `options_ui` supported too.

### Please complete the following information:

- Library Version: 3.3.0
- Operating System: MacOS Catalina
- Browser: Chrome version 84.0.4147.105 (Official Build) (64-bit)
- Node Version: 12.18.3

### Additional context

The solution may simply be a matter of including `options_ui` into derivedFiles HTML array around here
https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/53de0949378e7b6ab3866a6f671d9c3dc72407f2/src/manifest-input/manifest-parser/index.ts#L71 

Semi related to [Issue 27](https://github.com/extend-chrome/rollup-plugin-chrome-extension/issues/27)

**Comment by jacksteamdev** [comment]
@WillNeill This would be a welcome PR! 😊 The solution you suggested is perfect.

I won't be able to get to this for a few weeks... anyone who wants to contribute is welcome! 💯

### What needs to be done

- [ ] Write tests
- [ ] Fix bug

We'll need to add a test for this use case. We could add it to `__tests__/e2e__basic.test.ts` and `__fixtures__/extensions/basic/manifest.json`, and create the associated files (`options-ui.html`) from the [Google example docs](https://developer.chrome.com/extensions/options) you mentioned.

We can add `get(manifest, 'options_ui.page')` to the array you mentioned.

https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/53de0949378e7b6ab3866a6f671d9c3dc72407f2/src/manifest-input/manifest-parser/index.ts#L68-L75

**Comment by WillNeill** [comment]
Hey @jacksteamdev, I'm happy to submit a PR for this.

Just to note that options as Tab or Embedded seem to be mutually exclusive. It would be error prone to create both tests within the current `basic` case where `options_page` and `options_ui` would need to exist in the same manifest.json.

For example, the following in a manifest.json file should throw an error:

```JSON
{
  "name": "My extension",
  ...
  "options_page": "options.html",
  "options_ui": {
    "page": "options.html",
    "open_in_tab": false
  },
  ...
}
```

The more stable test solution might be to duplicate `basic` as `options-ui` with associated `__tests__/e2e__options-ui.test.ts`, and `__fixtures__/extensions/options-ui/manifest.json` and files.

Wanted to check with you first whether this sounds sensible, or you have alternate idea.

**Comment by jacksteamdev** [comment]
@WillNeill Sounds great! 

I agree, it should be one or the other. I tried loading the following `manifest.json` into Chrome on Linux and Windows.

```json
```

I'll leave it to your discretion whether we should throw an error in this case. If you do decide to implement this

**Comment by jacksteamdev** [comment]
Closed this by mistake. Hit `ctrl+enter` by mistake. C'mon GitHub! That's pretty agressive.

**Comment by jacksteamdev** [comment]
@elmaike @edemagbenyo @jones-sam @WillNeill Thanks everybody for your help! Contributers are always welcome here.
