### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#57]
### Is your feature request related to a problem? Please describe.

It's not a problem yet, but it will become one in the future.
Manifest v2 will become deprecated at some point, which will be replaced by [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/).
I watched a little bit of the Chrome Dev Summit, and there I heard that the first version of Manifest v3 will hit Chrome Canary (I believe) around mid-January 2021.

### Describe the solution you'd like

Begin reworking the plugin on a separated branch and make it to be the master branch when Manifest v2 will go deprecated.
FYI, Google has made a [migration guide](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/).

**Comment by rick-stevens** [comment]
V3 has been out for a while now and Google urges V2 users to migrate. Any update on this?
