### ISSUE TITLE
Using Svelte

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#58]
I wish to use [Svelte](https://svelte.dev) with [Svelte Materialify](https://github.com/TheComputerM/svelte-materialify) in my browser extension.
In my specific case, I only have a popup page, so I wish to use these there.
[This is an example repo](https://github.com/avi12/svelte-materialify-test).
Basically, so far I am able to load up JavaScript, but not any styles, and I'm not sure what Rollup configuration is missing.

**Comment by avi12** [comment]
After further investigation, I'm pretty sure that I need to specify beforehand in the HTML the following:
```html
<link rel="stylesheet" href="bundle.css">
```
The problem is that this file will only be created when [`css()`](https://github.com/avi12/svelte-materialify-test/blob/main/rollup.config.js#L35)'s function gets called by Rollup, but this Chrome plugin demands the CSS to be available as the Rollup configuration executes

**Comment by AmySteam** [comment]
We suggest using `rollup-plugin-postcss` [link](https://github.com/egoist/rollup-plugin-postcss#readme). 
You can also use it to [bundle scss files](https://github.com/egoist/rollup-plugin-postcss#with-sassstylusless) 

I made the following changes to these files and I got it working. The css will bundled into the popup.js file

**popup.js**
``` javascript
import Popup from "./components/Popup.svelte";
import "./popup.css";

new Popup({
  target: document.body,
});
```

**popup.css**
``` css
button {
  color: red;
}

```
And I changed the **rollup.config.js** plugins 

```javascript
  
  plugins: [
    chromeExtension(),
    !production && simpleReloader(),
    resolve({
      browser: true,
      dedupe: ["svelte"],
    }),
    commonjs(),
    svelte({
      compilerOptions: {
        dev: !production,
      },
      preprocess: preprocess({
        scss: {
          includePaths: ["theme"],
        },
      }),
    }),
    postcss({
      plugins: [],
    }),
    emptyDir(),
    production && terser(),
    production && zip({ dir: "dist_packed" }),
  ],
```
Hope this helps!

**Comment by avi12** [comment]
Sadly this configuration doesn't resolve my problem, as no `popup.css` is being created.

**Comment by AmySteam** [comment]
I thought about adding https://github.com/egoist/rollup-plugin-postcss#extract. It says it creates it extracts the CSS to the same location where JS file is generated but with .css extension, but I haven't tried it.

**Comment by jacksteamdev** [comment]
@avi12 It looks like `rollup-plugin-svelte` will process and output CSS files by itself. This means that we need to have a way to make `rollup-plugin-chrome-extension` ignore css files.

It should be relatively easy to add `include` and `exclude` options using `createFilter` from [`@rollup/pluginutils`](https://github.com/rollup/plugins/tree/master/packages/pluginutils). `include` doesn't really make much sense to me, but I guess we should be thorough.

I'll get around to this when I can, but PRs are welcome! Just be sure to add some tests so we know everything is doing what we want. 🧐

**Comment by jacksteamdev** [comment]
We've added a link to a boilerplate that show how to use Svelte with this plugin.
