### ISSUE TITLE
simpleReloader auto closes tab with popup.html

### ISSUE THREAD

**Issue by cat-ico** [extend-chrome/rollup-plugin-chrome-extension#71]
### Google search terms

chrome extension popup reload
### Describe the bug
When popup.html is open in a separate tab - `chrome-extension://id_of_application/popup.html`, simpleReloader causes the tab to close instead of being reloaded.

### How do we reproduce?
Open extension popup in new tab - `chrome-extension://id_of_application/popup.html`

### Expected behavior
Tab with popup should reload (or at least stay opened)

### Actual behavior
Tab with popup is closed when extension reloads via simpleReloader

### Please complete the following information:

- Library Version: 3.5.4
- Operating System: MacOS 10.14.6
- Browser: Chrome 89.0.4389.90
- Node Version: 14.4.0

**Comment by jacksteamdev** [comment]
@cat-ico The simple reloader reloads the background page whenever Rollup outputs a new build. HTML pages (options, popup, etc...) hosted on an extension belong to the background process, open pages are killed when the background page reloads.

### Why no HMR?

Chrome extensions have a special script-based development environment, and Chrome loads all the resources from disk. We need a server-based environment to get the UI developer experience we're used to with HMR and Fast Refresh.

A more complex reloader could theoretically use [Nollup](https://github.com/PepsRyuu/rollup-plugin-react-refresh) and a service worker to control module loading and support real HMR... this would be really exciting! PR's are welcome!

### Workarounds

I use Storybook for UI intensive Chrome extension page development. It's nice b/c you don't have to mess with navigating to the view/state you're working on.

Storybook runs in a normal browser environment and doesn't have access to the Chrome API, so you'll need to mock the Chrome API. [React Context is one of many solutions for this.](https://storybook.js.org/docs/react/workflows/build-pages-with-storybook#mocking-connected-components)

You could even just run a script that mocks the methods from `window.chrome` that you need to use. In that case you could just use something like Vite!

**Comment by cat-ico** [comment]
@jacksteamdev But does the background page need to be reloaded when only popup changes? 
Thanks for the workaround suggestions. I'll check those out.

**Comment by jacksteamdev** [comment]
@cat-ico Vite support with HMR for popups is currently in beta, see #117
