### ISSUE TITLE
Is compatible for Vite？

### ISSUE THREAD

**Issue by StarkShang** [extend-chrome/rollup-plugin-chrome-extension#73]
### Is your feature request related to a problem? Please describe.

I am using vite and vue3 to build a chrome extension. I would like using this plugin to bundle codes. I try to add this plugin in vite and find it not compatible. 

### Describe the solution you'd like

Vite has given a compatible solution described [here](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility)

**Comment by jacksteamdev** [comment]
Quoting the vite docs:

> In general, as long as a Rollup plugin fits the following criterias then it should just work as a Vite plugin:
> 
> 1. It doesn't use the moduleParsed hook.
> 2. It doesn't have strong coupling between bundle-phase hooks and output-phase hooks.

Unfortunately, this plugin falls in the second category. :disappointed:

**Comment by jacksteamdev** [comment]
@StarkShang Vite support is currently in beta.
