### ISSUE TITLE
When default_popup is not configured, rollup will not bundle it

### ISSUE THREAD

**Issue by xlzy520** [extend-chrome/rollup-plugin-chrome-extension#74]
### Describe the bug
When default_popup is not configured, rollup will not bundle it，but i want to use `chrome.windows.create`create this popup.

```js
chrome.windows.create({
      url: 'pages/popup/index.html',
})
```

### How do we reproduce?

1. in background.js
```js
console.log('background script12')
let currentId = null

chrome.browserAction.onClicked.addListener(function (tab) {
  var w = 1000;
  var h = 600;
  var left = Math.round((screen.width / 2) - (w / 2));
  var top = Math.round((screen.height / 2) - (h / 2));
  if (currentId) {
    chrome.windows.update(currentId, {
      focused: true
    })
  }else {
    chrome.windows.create({
      url: 'pages/popup/index.html',
      width: w,
      height: h,
      focused: true,
      'left': left,
      'top': top,
      type: 'popup'
    }, window => {
      currentId = window.id
    });
  }
  
});


```
2. in manifest.json, clear browser_action

### Screenshots

![image](https://user-images.githubusercontent.com/28336270/115106456-94303f00-9f97-11eb-84ed-a52ae11fa48b.png)

### Please complete the following information:

- Library Version: 3.5.6
- Operating System: Mac
- Browser: Chrome
- Node Version: 14

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/115106626-7b745900-9f98-11eb-89f1-d9c3c9d60d04.png)

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/115107148-9f856980-9f9b-11eb-9fd4-cd476c99d785.png)
Temporary solution

**Comment by xlzy520** [comment]
tihs window  by `chrome.window.create` be closed  when I update code. but [awesome-chrome-extension-boilerplate](https://github.com/tjx666/awesome-chrome-extension-boilerplate) hot module replacement is ok.

**Comment by jacksteamdev** [comment]
Just for future reference, you can always put files in the Rollup config input field:

```javascript
// rollup.config.js
export default {
  ...
  input: ['src/manifest.json', 'src/popup.html'],
  plugins: [chromeExtension()]
  ...
}
```

Or in the manifest in `web_accessible_resources`:

```jsonc
// manifest.json
{
  web_accessible_resources: ['popup.html']
}
```
