### ISSUE TITLE
[!] Error: Invalid substitution "../node_modules/nsfwjs/dist/index" for placeholder "[name]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.

### ISSUE THREAD

**Issue by maifeeulasad** [extend-chrome/rollup-plugin-chrome-extension#77]
### Google search terms
`rollup Error: Invalid substitution " for placeholder "[name]"`

### Describe the bug

When building getting an error saying :
```
[!] Error: Invalid substitution "../node_modules/nsfwjs/dist/index" for placeholder "[name]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.
```

### How do we reproduce?

Clone and checkout on: https://github.com/maifeeulasad/chrome-sfw/tree/24da719df455e17eddbb148126af5b3234388573

### Expected behavior

It used to work. I mean build without error.

### Please complete the following information:

- Library Version: `^3.5.2`
- Operating System: `Ubuntu 20.04 LTS`
- Browser: `91.0.4472.106 (Official Build) (64-bit)`
- Node Version: `v14.17.1`

### Additional context

Found something here: https://github.com/alfredosalzillo/rollup-plugin-multi-input

But this is not even on my dependency.

**Comment by jacksteamdev** [comment]
Hey @maifeeulasad! It looks like your dependencies were out of date, so the warning you got was kind of cryptic, but this is a Rollup problem.

After I updated any Rollup related dependencies to the latest version, I got the warnings below. It looks like `@tensorflow/tfjs-node` uses a library with circular dependencies. Here's a link to [the issue](https://github.com/joyent/node-sshpk/issues/42) to get you started.

```
(!) Circular dependencies
node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/key.js
node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> /media/jack/Storage/Documents/GitHub/chrome-sfw/node_modules/sshpk/lib/key.js?commonjs-proxy -> node_modules/sshpk/lib/key.js
node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/fingerprint.js
...and 42 more
(!) Plugin node-resolve: preferring built-in module 'punycode' over local alternative at '/media/jack/Storage/Documents/GitHub/chrome-sfw/node_modules/punycode/punycode.es6.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@tensorflow/tfjs-layers/dist/layers/convolutional_recurrent.js
 8:  * =============================================================================
 9:  */
10: var __rest = (this && this.__rest) || function (s, e) {
                  ^
11:     var t = {};
12:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
...and 1 other occurrence
created dist in 13s
```

**Comment by jacksteamdev** [comment]
Closing since this is a Rollup issue.
