### ISSUE TITLE
Using `web_accessible_resources` to copy the official i18n `_locales` folder removes the `_`

### ISSUE THREAD

**Issue by rick-stevens** [extend-chrome/rollup-plugin-chrome-extension#78]
### Google search terms

rollup-plugin-chrome-extension web_accessible_resources _locales

### How do we reproduce?

1. Create a `src/_locales/en/messages.json` file ([specs](https://developer.chrome.com/docs/extensions/reference/i18n/))
2. Add the folder to `src/manifest.json`:

```
{
  "web_accessible_resources": ["_locales/**/*.json"]
}
```

### Expected behavior

`src/_locales/**/*.json` being copied to `dist/_locales`.

### Actual behavior

`src/_locales/**/*.json` being copied to `dist/locales`.

### Screenshots

![image](https://user-images.githubusercontent.com/7610021/123544249-b04c1b80-d752-11eb-911f-aae68a0bce07.png)

### Please complete the following information:

- Library Version: 3.5.7
- Operating System: macOS 11.4
- Browser: _unrelated_
- Node Version: 14.17.1

### Additional context

Should be pretty straightforward.

**Comment by rick-stevens** [comment]
Thanks, I've done something similar for the time being 👍🏼

**Comment by AmySteam** [comment]
Hi @rick-stevens! We've added _locales support on the beta release `npm i rollup-plugin-chrome-extension@beta -D
`. Could you give it a can test run on your MV2 extension? 🧐  (MV3 support is not finished yet).

It should work without adding the _locales in the web accessible resources folder 😄

**Comment by rick-stevens** [comment]
That's great! I've temporarily moved to a custom Vite stup to support MV3, so I can't easily test in my current project. But the reproduction steps are quite simple and not related to a specific project structure. Happy that works now. Awaiting MV3 support! 🙏🏼

**Comment by AmySteam** [comment]
@rick-stevens Have you been able to get HMR working with vite? 🤔 We'll be working on the reloader next week and I wanted to know what others are using for reloading in all the different contexts (background, content scripts, etc) during development.

**Comment by grinono** [comment]
i tried to copy the transalation folder, it's creating the folder for sec, but then it's removed somehow. any idea how to resolve this?

``` import copy from 'rollup-plugin-copy' ```

```

 copy({
      targets: [
        { src: 'src/_locales/**/*.json', dest: 'dist/_locales' },
      ]
    }),
```

**Comment by grinono** [comment]
resolved with :    

```
import execute from 'rollup-plugin-execute'

 execute('yarn postbuild && yarn copy')
```

where running cp cli commands

**Comment by rick-stevens** [comment]
Sorry, I havent. I went for quick and dirty:
```json
{
  "scripts": {
    "build:background": "vite build --config background.vite.config.js",
    "build:content": "vite build --config content.vite.config.js",
    "build:options": "vite build --config options.vite.config.js",
    "build": "rimraf dist && concurrently yarn:build:*"
  }
}

```

**Comment by rick-stevens** [comment]
> @rick-stevens Have you been able to get HMR working with vite? 🤔 We'll be working on the reloader next week and I wanted to know what others are using for reloading in all the different contexts (background, content scripts, etc) during development.

Sorry, I havent. I went for quick and dirty:
```json
{
  "scripts": {
    "build:background": "vite build --config background.vite.config.js",
    "build:content": "vite build --config content.vite.config.js",
    "build:options": "vite build --config options.vite.config.js",
    "build": "rimraf dist && concurrently yarn:build:*"
  }
}
```
And used the `/public` folder for the manifest, locales, icons and CSS.
