### ISSUE TITLE
Manifest v3 support

### ISSUE THREAD

**Issue by vanvuongngo** [extend-chrome/rollup-plugin-chrome-extension#82]
### Is your feature request related to a problem? Please describe.

I tried to use your plugin but when I build my project with manifest v3 then an error message says that the maximum manifest version is only v2 :(

### Describe the solution you'd like

Allow a `manifest.json` which contains a more secure and performance optimized browser API:
```
    "manifest_version": 3,
```

### Describe alternatives you've considered

Stop using your plugin and wait for an update.

**Comment by avi12** [comment]
Duplicate of #79
