### ISSUE TITLE
suggested_keys should allow numeric keys

### ISSUE THREAD

**Issue by areohbe** [extend-chrome/rollup-plugin-chrome-extension#84]
Per [Chrome API docs](https://developer.chrome.com/docs/extensions/reference/commands/#supported-keys).

https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/5722a521d8a6be714e3a0fc98b253e22f4277bc4/manifest.schema.json#L71

Unless this was intentional, will submit a PR later today.

**Comment by jacksteamdev** [comment]
That would be great!
