### ISSUE TITLE
Cannot import NodeJS modules

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#86]
### Describe the bug
I want to make an extension that uses [@ffmpeg/ffmpeg](https://npm.im/@ffmpeg/ffmpeg).
Except, by doing
```ts
import { createFFmpeg } from "@ffmpeg/ffmpeg";
```
in the background script, it apparently also attempts to import JSON(s).

If I add to `rollup.config.js`:
```js
import json from "@rollup/plugin-json";

export default {
  // ...
  plugins: [
    chromeExtension(),
    json(),
    resolve(),
    commonjs(),
    emptyDir()
  ]
}
```
then, after running this Rollup configuration, inspecting the background page will reveal the following error:
```
Uncaught (in promise) TypeError: Failed to resolve module specifier "util". Relative references must start with either "/", "./", or "../".
```

### How do we reproduce?
1. ```shell
    npx degit "kyrelldixon/svelte-tailwind-extension-boilerplate#main" your-extension-name
    yarn
    yarn add @ffmpeg/ffmpeg && yarn add -D @rollup/plugin-json
    ```
1. Add the above snippets in the appropriate places.
1. Run the Rollup configuration.
1. Load the extension to Chrome.
1. Inspecting the background page will reveal the above error.

### Expected behavior
Being able to import `@ffmpeg/ffmpeg` without any problem.

### Actual behavior
Getting the error above.
<!-- A clear and concise description of what did happen. -->

### Please complete the following information:

- Library Version:: 3.5.2
- Operating System: Windows 10 x64 21H1
- Browser: Google Chrome Canary 94.0.4584.0
- Node Version: 14.7.3

### Additional context
I made a [sample project](https://github.com/avi12/youtube-downloader_old) (without using `rollup-plugin-chrome-extension`) that _does_ import both `@ffmpeg/ffmpeg` and uses `@rollup/plugin-json`.

**Comment by jacksteamdev** [comment]
@avi12 Thanks for putting together an example repo! Fortunately, this doesn't look like a problem specific to `rollup-plugin-chrome-extension` :sweat_smile: 

There should be some external dependency warnings from Rollup when you build this project. The error comes from [this line](https://github.com/ffmpegwasm/ffmpeg.wasm/blob/9b8a5f7723dd38143602a259828c3d95eb49bcd0/src/node/fetchFile.js#L1) in `@ffmpeg/ffmpeg`, where they are importing the NodeJS `util` module. This is a long standing problem with Rollup and browser builds in general. 

I would try this [up to date Rollup plugin](https://github.com/snowpackjs/rollup-plugin-polyfill-node) maintained by Snowpack, but YMMV. :man_shrugging:

**Comment by avi12** [comment]
As I mentioned, I get the error I mentioned only when I'm using `rollup-plugin-chrome-extension`
In the sample project I linked, where I used Rollup with `@rollup/plugin-json`, this problem didn't occur
