### ISSUE TITLE
prettier dependency?

### ISSUE THREAD

**Issue by ogrotten** [extend-chrome/rollup-plugin-chrome-extension#91]
https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/5722a521d8a6be714e3a0fc98b253e22f4277bc4/package.json#L44

I discovered today that this entry was at the root of problems I was having with code formatting, as it was blocking use of project-level `.prettierrc` used to format Svelte. 

By removing the above line, removing `package-lock.json`, and then re-running `npm i`, `*.svelte` are now formatted as expected.

### Expected Behavior / Situation
All levels of Svelte files are code formatted.

### Actual Behavior / Situation
Code inside `<script>` tags is ignored by code formatting.

### Modification Proposal
I don't know the code well enough to say what could keep this prettier dependency from leaking out.

**Comment by jacksteamdev** [comment]
@ogrotten Weird. I've had that same problem, so I'm glad that you found a solution! Svelte is great for Chrome Extensions, isn't it?

I'll see if we can remove prettier. Thanks for isolating the problem.

**Comment by ogrotten** [comment]
The removal isn't a fix. The compiler complains about prettier is missing. I just did that to see if that instance of prettier was at the core of my problem, and it was. 

Other than that, I dug around. . . there's only 1 real reference to it, and it appears to be rewriting the derived html output to be prettied for source. I tried to modify it, but I don't know all the ins n outs.

I don't think prettier is necessary tho... all modern browsers (even safari) will reformat and Pretty Print even the jankiest html source in their inspector.

**Comment by ogrotten** [comment]
Oh btw, the way I fixed my problem:

1. change rollup-plugin-chrome-extension/package.json > to read ` "prettier": "^2.3.2", ` (latest stable)
2. `npm i prettier` at project level. 
3. del `package-lock.json`
4. `npm i` at project level. 

I didn't have prettier installed at proj level before, and that alone may have fixed it.

**Comment by jacksteamdev** [comment]
You're right tho, we didn't need it!

I was able to remove it, and prettier is only a dev dependency in the latest beta release.

I'm in the middle of adding MV3 support, but all the MV2 tests are passing, so it should work just fine.

**Comment by ogrotten** [comment]
Badass! Glad to have helped!
